WIP 通过 SourceGenerator 生成代码
dotnet-campus/SourceFusion pull request #38
Opened 2023-06-05 06:44 UTC by lindexi

2023-06-14 03:37 UTC, walterlv requested changes

2023-06-14 03:37 UTC, walterlv commented on SourceFusion.sln
>  ﻿
```xml
<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
```

如果计划继续兼容 net45，那就加上这个吧！这样大家都能打开即编译，不用配环境。

2023-06-14 03:37 UTC, walterlv commented on src/TelescopeSourceGenerator/Analyzers/Context_/AssemblyCandidateClassParseResult.cs
> +
多出了空格

2023-06-14 03:37 UTC, walterlv commented on src/TelescopeSourceGenerator/Analyzers/TelescopeIncrementalGenerator.cs
> +                            .Any(subNode => subNode.IsKind(SyntaxKind.AttributeTargetSpecifier));
```csharp
return syntaxNode is AttributeListSyntax s
    && s.Attributes.Any(x => typeof(MarkExportAttribute).FullName.Contains(x.Name.ToString()));
```

使用此语法过滤，可以使更少的语法节点进入到后面的语义分析中来，也许可以提升 IDE 使用体验？

2023-06-14 03:37 UTC, walterlv commented on src/TelescopeSourceGenerator/Analyzers/Context_/MarkExportAttributeParseResult.cs
> +{
```csharp
/// <summary>
/// 获取表示失败的特性解析结果。
/// </summary>
public static MarkExportAttributeParseResult Failure { get; } = new MarkExportAttributeParseResult(false, default, default);
```

看到你有多处使用，放这里好些？

2023-06-14 03:37 UTC, walterlv commented on src/TelescopeSourceGenerator/Analyzers/Context_/MarkExportAttributeParseResult.cs
> +{
```csharp
/// <summary>
/// 获取表示失败的特性解析结果。
/// </summary>
public static MarkExportAttributeParseResult Failure { get; } = new MarkExportAttributeParseResult(false, default, default);
```

看到你有多处使用，放这里好些？

2023-06-14 03:37 UTC, walterlv commented on src/TelescopeSourceGenerator/Analyzers/dotnetCampus.Telescope.SourceGeneratorAnalyzers.csproj
> +
```xml
  <ItemGroup>
    <Compile Include="..\..\dotnetCampus.Telescope\*Attribute.cs" Link="Attributes\%(RecursiveDir)%(FileName)%(Extension)" />
  </ItemGroup>
```

这样，你可以在分析器代码里用上新鲜热乎的特性，而不用写死字符串。

2023-06-14 03:37 UTC, walterlv commented on src/TelescopeSourceGenerator/Analyzers/TelescopeIncrementalGenerator.cs
> +                        TypeInfo? GetTypeOfType(AttributeArgumentSyntax attributeArgumentSyntax)
GetTypeOfType -> GetTypeInfoFromArgumentTypeOfSyntax

虽然你原来的名称非常非常符合含义，但是它就像一个绕口令一样，理解起来不直观。所以，我建议改成后面的名字。

- 原：GetTypeOfType 获取 typeof 中的 Type
- 改：GetTypeInfoFromArgumentTypeOfSyntax 获取 TypeInfo 从 Argument 的 TypeOf 语法中

顺便分享一个绕口令：

Before was was was was was is.

2023-06-14 03:37 UTC, walterlv commented on src/TelescopeSourceGenerator/Analyzers/TelescopeIncrementalGenerator.cs
> +            (sourceProductionContext, generationCode) =>
generation -> 代
generated -> 生成的

2023-06-14 03:37 UTC, walterlv commented on src/TelescopeSourceGenerator/Analyzers/ExportedTypesCodeTextGenerator.cs
> +    private static string TypeSymbolToFullName(ITypeSymbol typeSymbol)
[NotNullWhenNotNull]

注意，你最后有一个可空返回。

2023-06-14 06:23 UTC, lindexi commented on src/TelescopeSourceGenerator/Analyzers/TelescopeIncrementalGenerator.cs
> +                            .Any(subNode => subNode.IsKind(SyntaxKind.AttributeTargetSpecifier));
暂时不想，保持，影响不大

2023-06-14 06:24 UTC, lindexi commented on src/TelescopeSourceGenerator/Analyzers/dotnetCampus.Telescope.SourceGeneratorAnalyzers.csproj
> +
先放字符串，后面也许打算修改为写入源代码而不是多程序集引用，到时候统一再改

2023-06-14 06:24 UTC, lindexi commented on src/TelescopeSourceGenerator/Analyzers/ExportedTypesCodeTextGenerator.cs
> +    private static string TypeSymbolToFullName(ITypeSymbol typeSymbol)
改成了完全不可空

2023-06-14 10:47 UTC, walterlv submitted a review, later dismissed

2023-06-14 10:47 UTC, walterlv commented on src/TelescopeSourceGenerator/Analyzers/TelescopeIncrementalGenerator.cs
> +                    // g
为什么注释了一个 `g`？

2023-06-30 07:28 UTC, walterlv approved these changes

2023-06-30 07:28 UTC, merged