Add native support for collecting attributed types.
dotnet-campus/SourceFusion pull request #6
Opened 2019-01-16 01:12 UTC by walterlv

2019-01-21 02:55 UTC, lindexi requested changes

2019-01-21 02:55 UTC, lindexi commented on src/SourceFusion.Tool/Assets/build/Package.targets
> +      <SourceFusionCommandArgLine Include=">" />
这里是否加上注释，使用高性能配置？

2019-01-21 02:55 UTC, lindexi commented on src/SourceFusion.Tool/CompileTime/CompileAttribute.cs
>              Name = name ?? throw new ArgumentNullException(nameof(name));
字符串可能是空

2019-01-21 02:55 UTC, lindexi commented on src/SourceFusion.Tool/Core/CompilingException.cs
> +        public CompilingException(params string[] errors)
需要这个值不为空

2019-01-21 02:55 UTC, lindexi commented on src/SourceFusion.Tool/Properties/AssemblyInfo.cs
> +//     此代码由工具生成。
这里推荐为英文

2019-01-21 02:55 UTC, lindexi commented on src/SourceFusion.Tool/Templates/TemplateTransformer.cs
> +        private readonly Regex _usingRegex = new Regex(@"using\sdotnetCampus\.SourceFusion[\.\w]*;\r?\n");
多次使用的正则使用编译

2019-01-21 02:55 UTC, lindexi commented on src/SourceFusion.Tool/Templates/ArrayPlaceholder.cs
> +public static class PlaceholderImpl
Impl 是内部的命名，不能将这个 public 请修改命名

2019-01-21 07:34 UTC, walterlv commented on src/SourceFusion.Tool/Properties/AssemblyInfo.cs
> +//     此代码由工具生成。
整份代码里面都用了中文，这个就保持中文吧……我想基本功能完成了之后再统一做本地化。

2019-01-22 06:01 UTC, lindexi approved these changes

2019-01-22 06:01 UTC, merged